### ISSUE TITLE
Jumploader v2.1.3: NoSuchElementException Crash

### ISSUE THREAD

**Issue by Cwoodyard** [comp500/Jumploader#21] opened 2021-04-20 03:00 UTC
been having issues with jumploader on my modpack and would like to see if you can look into it. Attached is the crash log. Server is running FabricLoader 0.11.2. 

[crash-2021-04-19_22.40.19-client.txt](https://github.com/comp500/Jumploader/files/6340342/crash-2021-04-19_22.40.19-client.txt)

**Comment by comp500** [comment] 2021-04-20 03:15
I don't think that crash is related to Jumploader, it's in lighting engine code. Does it occur without Jumploader?

**Comment by Cwoodyard** [comment] 2021-04-20 04:20
I believe so. Can you tell which mod would be calling the lighting code? If not i can look more in depth and thank you for the help. :)

**Comment by comp500** [comment] 2021-04-20 04:27
Could you add https://modrinth.com/mod/mixintrace to your mods folder and send the crash report with it included? That will add some more information to help you track down the mod that is modifying lighting code.

**Comment by comp500** [comment] 2022-01-23 18:48
Closing (can't reproduce, doesn't seem to be caused by Jumploader)

**Closed as completed by comp500** 2022-01-23 18:48 UTC
